### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by MACscr** [kmgalanakis/mailgun-dashboard#2]
Just curious on the state of this project. Is it working well for you? Could be useful for me as a starting point even though I would actually be modifying it to work within a codeigniter project instead of WP.

**Comment by kmgalanakis** [comment]
Overall it is working fine for me. I developed this for a client and it seems to have been very useful to him. I'm actively maintaining it even though it's not getting much attention.

If you need help or info, please let me know.

**Comment by MACscr** [comment]
Awesome. Any chance you could share a few screenshots?

- Mark

**Comment by kmgalanakis** [comment]
You can find a few here https://wordpress.org/plugins/dashboard-for-mailgun/
